services:

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123

    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: postgres
      DB_PASSWORD: password123

    ports:
      - "5000:5000"

volumes:
  postgres-data:
